trigger:
  branches:
    include:
      - master # Cambia al nombre de la rama que deseas sincronizar

pool:
  vmImage: 'ubuntu-latest'

variables:
 
  sourceURL: "https://$(azure_token)@dev.azure.com/MagicAzure/SolutionCore/_git/SolutionCore"
  destURL : "https://$(gitPat)@github.com/cristhian300/SolutionCore.git"
steps:


  - script: |
     
     mkdir copyrepo
     cd copyrepo 
     git clone --mirror  $(sourceURL)

     cd SolutionCore.git

     git remote rm origin
     git remote add --mirror=fetch origin $(destURL)
    displayName: 'Sincronizar con GitHub'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)