trigger:
  branches:
    include:
      - master # Cambia al nombre de la rama que deseas sincronizar

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_REPO_URL: "https://$(GitHubPAT)@github.com/cristhian300/SolutionCore.git"
  GITHUB_TOKEN: $(GitHubPAT) # GitHub PAT configurado en Azure DevOps como secreto
  sourceURL: "https://$(azure_token)@dev.azure.com/MagicAzure/SolutionCore/_git/SolutionCore"

steps:


  - script: |
     
     mkdir copyrepo
     cd copyrepo 
     git clone --mirror  $(sourceURL)

     cd SolutionCore.git

     git remote rm origin
       
    displayName: 'Sincronizar con GitHub'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)