trigger:
  branches:
    include:
      - master # Cambia al nombre de la rama que deseas sincronizar

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Realiza checkout del repositorio de Azure DevOps

  - task: Bash@3
    displayName: "Sincronizar con GitHub"
    inputs:
      targetType: 'inline'
      script: |
        # Configuraci칩n de usuario de Git
        git config --global user.name "cristhian300"
        git config --global user.email "cristhian_666win@hotmail.com"

        # A침adir el remoto de GitHub con autenticaci칩n usando el token
        git remote add github https://$(GITHUB_TOKEN)@github.com/cristhian300/SolutionCore.git

        # Forzar sincronizaci칩n con GitHub, preservando el historial de commits
        git push github master --force-with-lease
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)