trigger:
  branches:
    include:
      - master # Cambia al nombre de la rama que deseas sincronizar

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Realiza checkout del repositorio de Azure DevOps

  - task: Bash@3
    displayName: "Sincronizar con GitHub"
    inputs:
      targetType: 'inline'
      script: |
        # Configuraci칩n de usuario de Git
        git config --global user.name "cristhian300"
        git config --global user.email "cristhian_666win@hotmail.com"

        mkdir copyRepo
        Set-Location "$(Build.SourcesDirectory)/copyrepo"
         #cd copyRepo
        git clone --mirror  https://$(azure_token)@dev.azure.com/MagicAzure/SolutionCore/_git/SolutionCore
        Set-Location "$(Build.SourcesDirectory)/copyrepo/SolutionCore/"
        # Write-Host "*****Git removing remote origin****"
        git remote rm origin

        #Write-Output "*****Git remote add****"
        git remote add --mirror=fetch origin https://$(GITHUB_TOKEN)@github.com/cristhian300/SolutionCore.git
         #git remote add github https://github.com/cristhian300/SolutionCore.git
        #Write-Output "*****Git fetch origin****"
        git fetch https://$(azure_token)@dev.azure.com/MagicAzure/SolutionCore/_git/SolutionCore
         #git push -u github master
        #Write-Output "*****Git push to Azure Repos****"
        git push origin --all -f
            # A침adir el remoto de GitHub con autenticaci칩n usando el token
        #git remote add github  https://$(GITHUB_TOKEN)@github.com/cristhian300/SolutionCore.git

        #git checkout -b master
        # Forzar sincronizaci칩n con GitHub, preservando el historial de commits
        #git push github master --force-with-leas
       
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)