trigger:
  branches:
    include:
      - master # Cambia al nombre de la rama que deseas sincronizar

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_REPO_URL: "https://github.com/cristhian300/SolutionCore.git"
  GITHUB_TOKEN: $(GitHubPAT) # GitHub PAT configurado en Azure DevOps como secreto


steps:
  - checkout: self  # Realiza checkout del repositorio de Azure DevOps
    persistCredentials: true

  - script: |
      git config --global user.name "cristhian300"
      git config --global user.email "cristhian_666win@hotmail.com"
      git remote add github $(GITHUB_REPO_URL)
      git fetch github
      echo mostrado branch
      git checkout -b master
      git branch 
      git push github master
       
    displayName: 'Sincronizar con GitHub'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)