# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    git config  --global user.email "cristhian_666win@hotmail.com"
    git config  --global user.name "cristhian300"
     
     
    git remote add github  https://$(GITHUB_TOKEN)@github.com/cristhian300/SolutionCore
    git push github main --force
     git config --list
     echo $(GITHUB_TOKEN)
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

  env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)