trigger:
  branches:
    include:
      - master # Cambia al nombre de la rama que deseas sincronizar

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Realiza checkout del repositorio de Azure DevOps

  - task: Bash@3
    displayName: "Sincronizar con GitHub"
    inputs:
      targetType: 'inline'
      script: |
        # Configuración de usuario de Git
        git config --global user.name "cristhian300"
        git config --global user.email "cristhian_666win@hotmail.com"

        # Añadir el remoto de GitHub con autenticación usando el token
        git remote add github  https://$(GITHUB_TOKEN)@github.com/cristhian300/SolutionCore.git
 
        # Asegurarse de que el estado local está actualizado
        git fetch origin master
      

        # Crear el commit con los cambios
        git add -A
        git commit -m "Sincronización automática desde Azure DevOps"

        # Enviar los cambios a GitHub
        git push github master
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)