trigger:
  branches:
    include:
      - master # Cambia al nombre de la rama que deseas sincronizar

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_REPO_URL: "https://$(GitHubPAT)@github.com/cristhian300/SolutionCore.git"
  GITHUB_TOKEN: $(GitHubPAT) # GitHub PAT configurado en Azure DevOps como secreto


steps:


  - script: |
     
     mkdir copyrepo
     
     #$sourceURL = "https://$(azure_token)@dev.azure.com/MagicAzure/SolutionCore/_git/SolutionCore"
     #$sourceURL = "https://$(GITPAT)@$(GITREPO)"
     #$destURL = "https://$(AZUREREPOPAT)@$(AZUREPO)"

     cd copyrepo 
     git clone --mirror https://$(azure_token)@dev.azure.com/MagicAzure/SolutionCore/_git/SolutionCore

     #cd SolutionCore.git

      
       
    displayName: 'Sincronizar con GitHub'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)