trigger:
  branches:
    include:
      - master # Cambia al nombre de la rama que deseas sincronizar

pool:
  vmImage: 'ubuntu-latest'

variables:
  GITHUB_REPO_URL: "https://github.com/cristhian300/SolutionCore.git"
  GITHUB_TOKEN: $(GitHubPAT) # GitHub PAT configurado en Azure DevOps como secreto


steps:
  - checkout: self  # Realiza checkout del repositorio de Azure DevOps
    persistCredentials: true
  