version: '3.4'

services:

 

  configuration.gateway:
    image: ${DOCKER_REGISTRY-}configurationgateway
    container_name: gateway
    #expose:
    #  - 80
    ports:
      - 5052:80
    build:
      context: .
      dockerfile: Configuration.API.GateWay/Configuration.GateWay/Dockerfile

  solutioncore:
    image: ${DOCKER_REGISTRY-}solutioncore
    container_name: solutioncore_api
    #expose:
    #  - 5053
    ports:
      - 5053:80
    build:
      context: .
      dockerfile: SolutionCore/Dockerfile
    depends_on:
      - dbCore

  web_core:
    image: ${DOCKER_REGISTRY-}webcore
    container_name: web_core
    ports:
      - 44512:80
    build:
      context: .
      dockerfile: web_core/Dockerfile

  dbCore:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: dbCore
    environment: 
     ACCEPT_EULA: "Y"
     SA_PASSWORD: "Cris@cristhian"
     #MSSQL_PID: Express
     
    ports:
      - 1433:1433
    volumes:
      - c:/BdSqlDocker/sqlserver-data:/var/opt/mssql/data
      - c:/BdSqlDocker/sqlserver-data:/var/opt/mssql/log
      - c:/BdSqlDocker/sqlserver-data:/var/opt/mssql/secrets 