version: '3.4'

services:
  configuration.gateway:
    image: ${DOCKER_REGISTRY-}configurationgateway
    container_name: gateway
    #expose:
    #  - 80
    ports:
      - 5052:80
    build:
      context: .
      dockerfile: Configuration.API.GateWay/Configuration.GateWay/Dockerfile

  solutioncore:
    image: ${DOCKER_REGISTRY-}solutioncore
    container_name: solutioncore_api
    #expose:
    #  - 5053
    ports:
      - 5053:80
    build:
      context: .
      dockerfile: SolutionCore/Dockerfile

