version: '3.4'

services:

  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=cristhian
    ports:
      - 1433:1433

  configuration.gateway:
    image: ${DOCKER_REGISTRY-}configurationgateway
    container_name: gateway
    #expose:
    #  - 80
    ports:
      - 5052:80
    build:
      context: .
      dockerfile: Configuration.API.GateWay/Configuration.GateWay/Dockerfile

  solutioncore:
    image: ${DOCKER_REGISTRY-}solutioncore
    container_name: solutioncore_api
    #expose:
    #  - 5053
    ports:
      - 5053:80
    build:
      context: .
      dockerfile: SolutionCore/Dockerfile
    depends_on:
      - db

  web_core:
    image: ${DOCKER_REGISTRY-}webcore
    container_name: web_core
    ports:
      - 44512:80
    build:
      context: .
      dockerfile: web_core/Dockerfile

 
