apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-seguridad
  template:
    metadata:
    
      labels:
        app: microservice-seguridad
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server
          ports:
            - containerPort: 1433
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "$VaxiDrez2025"