export class LoginRequest {
    userName: string;
    password: string;
}

export class GetTokenResponse {

  token: string
}


// Generated by https://quicktype.io

  export interface ITokenResponse {
  code:    number;
  message: string;
  payload: ITokenPayLoad;
}

export interface ITokenPayLoad {
  token:        string;
  refreshToken: string;
  expiration:   string;
  name:         string;
  username:     string;
}
