// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SolutionCore.Api.DataAcces.Infrastructure.Data.Entities
{
    public partial class RolesUser
    {
        public RolesUser()
        {
            Usuarios = new HashSet<Usuario>();
        }

        public int RoleId { get; set; }
        public string RoleCode { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }

        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}