// Generated by https://quicktype.io

export interface ProductResponse {
  ok: boolean;
  products: Array<Product>;
}

export interface Product {
  name: string;
  details: string;
  price: number;
  enable: boolean;
  uid: string;
  image: string;
}
